Algoritmo "par impar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/11/2021
Var

num: inteiro

Inicio

escreval("insira um numero")
leia (num)

se (num mod 2)=0 entao
   escreval("esse numero e PAR")
senao
     escreval("esse numero e IMPAR")
fimse

Fimalgoritmo